name: jupyter-book-deploy

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Python 3.12.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build book
        run: jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy
        uses: actions/deploy-pages@v4
